import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Section/Hero";
import About from "../components/Section/About";
import Services from "../components/Section/Services";
import Contact from "../components/Section/Contact";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ant Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <About />
      <Services />
      <Contact />
    </div>
  );
};

export default Home;
