import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Sections/Hero";
import Portfolio from "../components/Sections/Portfolio";
import Story from "../components/Sections/Story";
import Contact from "../components/Sections/Contact";

const Home: NextPage = (projects) => {
  return (
    <div>
      <Head>
        <title>Gareth Hind || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      {/* <Portfolio projects={projects}/> */}
      <Story />
      <Contact />
    </div>
  );
};

export default Home;
